[project]
name = "pc-lego-spike-simulator"
version = "0.1.0"
description = "A Python based simulator for Lego Spike Python APIs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
